version: '3'
services:
  db:
    # https://hub.docker.com/_/postgres
    image: mdillon/postgis
    ports:
      # ホストの5432ポートで待ち受け
      - 5432:5432
    volumes:
      - ./setup/db/init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    environment:
      # (必須)特権ユーザのパスワード
      POSTGRES_PASSWORD: root
      # 特権ユーザのユーザ名
      POSTGRES_USER: root
      # 初期で作成するデータベース
      # 省略するとユーザ名と同じになる
      POSTGRES_DB: atlasaz
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always
    networks: 
      - front
  db_fts:
    # https://hub.docker.com/_/postgres
    image: groonga/pgroonga:latest-alpine-11-slim
    ports:
      # ホストの5432ポートで待ち受け
      - 5433:5433
    volumes:
      - ./setup/db_fts/init:/docker-entrypoint-initdb.d
      - db-fts-data:/var/lib/postgresql/data
    environment:
      # (必須)特権ユーザのパスワード
      POSTGRES_PASSWORD: root
      # 特権ユーザのユーザ名
      POSTGRES_USER: root
      # 初期で作成するデータベース
      # 省略するとユーザ名と同じになる
      POSTGRES_DB: atlasaz
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      PGPORT: 5433
    restart: always
    networks: 
      - front
  pgadmin4:
    # https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
    image: dpage/pgadmin4:latest
    ports:
      # ホストの8081ポートで待ち受け
      - 8081:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin:z
    environment:
      # 初期ユーザとパスワード
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on: 
      - db
    restart: always
    networks: 
      - front
  backup:
    image: busybox
    volumes:
      - ./backup:/backup
      - db-data:/data/db-data
      - db-fts-data:/data/db-fts-data
      - pgadmin-data:/data/pgadmin-data
    restart: always
    networks: 
      - front
    tty: true
networks: 
  front:
volumes:
  db-data:
  db-fts-data:
  pgadmin-data:
